chore: 123281 add some commands for debugging

diff --git a/docker-compose.ci.yml b/docker-compose.ci.yml
--- a/docker-compose.ci.yml
+++ b/docker-compose.ci.yml
@@ -236,9 +236,15 @@ services:
     init-elasticsearch-secrets:
         image: busybox:latest
         command: |
-            mkdir -p /secrets
+            ls -la /run/secrets/ || echo "Cannot list /run/secrets"
+            ls -la /secrets/
+
             cp /run/secrets/elasticsearch_password /secrets/elasticsearch_password
+
+            echo "Changing permissions..."
             chmod 600 /secrets/elasticsearch_password
+
+            echo "Changing ownership..."
             chown 1000:0 /secrets/elasticsearch_password
         volumes:
             - shared-secrets:/secrets
