config: 786383 use a debug log

diff --git a/.github/workflows/dockerfile-builder.yaml b/.github/workflows/dockerfile-builder.yaml
--- a/.github/workflows/dockerfile-builder.yaml
+++ b/.github/workflows/dockerfile-builder.yaml
@@ -56,6 +56,8 @@ jobs:
             echo "built_count=0" >> $GITHUB_OUTPUT
             exit 0
           fi
+          
+          echo "$CHANGED_DIRS" | jq empty 2>&1 && echo "✅ CHANGED_DIRS is valid" || echo "❌ CHANGED_DIRS is invalid"
 
           CHANGED_DIRS=$(echo "${ALL_CHANGED_FILES}" | tr ' ' '\n' | xargs -I {} dirname {} | sort -u)
           CHANGED_DIRS_COUNT=$(echo "${CHANGED_DIRS}" | wc -l)
