config: 786383 add  error handling

diff --git a/.github/workflows/dockerfile-builder.yaml b/.github/workflows/dockerfile-builder.yaml
--- a/.github/workflows/dockerfile-builder.yaml
+++ b/.github/workflows/dockerfile-builder.yaml
@@ -90,7 +90,13 @@ jobs:
                 
                 IMAGES_JSON="${IMAGES_JSON}{\"name\":\"${IMAGE_NAME}\",\"sha\":\"${IMAGE_SHA}\",\"latest\":\"${IMAGE_LATEST}\"}"
                 BUILT_COUNT=$((BUILT_COUNT + 1))
+              else
+                echo "❌ Could not build: ${IMAGE_NAME}"
+                exit 1
               fi
+            else
+              echo "❌ No directory exists: ${file}"
+              exit 1
             fi
           done
           
